//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikhil_WebMobi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmpDetail
    {
        public int EmpID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string FGender { get; set; }
        public string DOB { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Department { get; set; }
    }
}
